Correct CI
monsieurbiz/SyliusRichEditorPlugin pull request #141
Opened 2021-04-21 13:51 UTC by clem21

2021-04-21 14:27 UTC, jacquesbh requested changes

2021-04-21 14:27 UTC, jacquesbh commented on .github/workflows/tests.yaml
> +
This is done below.

```
run: make test.composer
```

2021-04-21 16:16 UTC, jacquesbh requested changes

2021-04-21 16:16 UTC, jacquesbh commented on .github/workflows/tests.yaml
> +
Oops?

2021-04-22 07:36 UTC, maximehuran approved these changes

2021-04-22 09:03 UTC, lanfisis approved these changes

2021-04-22 11:48 UTC, jacquesbh requested changes
We could use a little rebase here :).

2021-04-26 09:29 UTC, jacquesbh approved these changes
Thank you @clem21! 🎉

2021-04-26 09:39 UTC, merged