Use same method to manage tags in display and paste
monsieurbiz/SyliusRichEditorPlugin pull request #204
Opened 2023-08-22 13:15 UTC by maximehuran

2023-09-05 16:47 UTC, jacquesbh approved these changes

2023-09-05 16:58 UTC, jacquesbh requested changes

2023-09-05 16:58 UTC, jacquesbh commented on assets/js/app.js
> -    }
This is very important. You need to understand the exclusivity.

`-tag` is different than `foo -tag`.

`-tag` alone means `all components without the `tag` tagged ones`.
`foo -tag` means `all foo tagged components without the `tag` tagged ones`.

And not `all elements, including foo ones, without `tag` tagged ones`.

2024-06-18 08:03 UTC, maximehuran commented
We need to check this issue in another way

2024-06-18 08:03 UTC, closed without merging