Switch form PEL to SunEditor as default WYSIWYG editor
monsieurbiz/SyliusRichEditorPlugin pull request #219
Opened 2024-04-04 14:49 UTC by lanfisis

Two main things of this PR:
- add capability to add new WYSIWYG  (more) easily with a thin abstraction layer
- add [suneditor.js](https://github.com/JiHong88/suneditor/)  as the default WYSIWYG instead of PELL

## Screenshots

<img width="1630" alt="image" src="https://github.com/monsieurbiz/SyliusRichEditorPlugin/assets/872996/33e2deab-79b7-41e0-95a6-479c82e8c58f">

<img width="964" alt="image" src="https://github.com/monsieurbiz/SyliusRichEditorPlugin/assets/872996/969d9662-ff91-4a05-89bf-a8e3d4eb972c">

<img width="1557" alt="image" src="https://github.com/monsieurbiz/SyliusRichEditorPlugin/assets/872996/bf191ea7-aecf-48dd-a1c8-f7ac06e8c4b3">

2024-04-05 12:18 UTC, delyriand requested changes
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**❔ question:** ‏isn't it possible to keep the peel in editor (default for transition time?) in addition to SunEditor?

2024-04-08 07:47 UTC, maximehuran approved these changes
We need to release it with `2.5.0` version and may write an upgrade guide if needed

2024-04-17 10:01 UTC, lanfisis commented
> **❔ question:** ‏isn't it possible to keep the peel in editor (default for transition time?) in addition to SunEditor?

I think as @maximehuran that we should forget PEL. The ever created PEL  HTML content are very simple because PEL is simple and there is no problem to display it on SunEditor

2024-04-17 11:25 UTC, delyriand approved these changes

2024-04-17 13:17 UTC, etienne-monsieurbiz approved these changes

2024-04-25 11:58 UTC, merged