Allow Sylius 1.11 to 1.13
monsieurbiz/SyliusRichEditorPlugin pull request #231
Opened 2024-06-18 17:54 UTC by maximehuran

- Remove recipes from plugin
- Update dependencies and workflows to use Sylius 1.13

2024-06-28 13:55 UTC, etienne-monsieurbiz requested changes

2024-06-28 13:55 UTC, etienne-monsieurbiz commented on README.md
> +```
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**❔ question:** Do we really need to have this command in red in the readme ?‏

2024-06-28 13:55 UTC, etienne-monsieurbiz commented on src/UiElement/UiElementFormOptionsTrait.php
> +            /** @phpstan-ignore-next-line */
<!-- Nitpicks are small, trivial, but necessary changes. Distinguishing nitpick comments significantly helps direct the reader's attention to comments requiring more involvement.  -->
**🤓 nitpick:** You can ignore this error like this when it's one line return : 
`/** @var array*/`
```suggestion
            /** @var array*/
```

‏

2024-06-28 13:55 UTC, etienne-monsieurbiz commented on src/UiElement/UiElementTrait.php
> +use PHPUnit\Framework\Assert;
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**🎯 suggestion:** It's probably not this Assert class that you want here‏

2024-07-02 09:41 UTC, etienne-monsieurbiz approved these changes
LGTM

2024-07-02 09:46 UTC, delyriand approved these changes

2024-07-02 09:47 UTC, merged