Add markdown element
monsieurbiz/SyliusRichEditorPlugin pull request #239
Opened 2024-09-05 15:00 UTC by maximehuran

- Add markdown UI Element
- Add highlight JS in shop
- Update README to add Markdown element
- Enable highlight JS in test app with another theme

2024-09-05 16:20 UTC, jacquesbh requested changes

2024-09-05 16:20 UTC, jacquesbh commented on assets/js/highlight.js
> +  document.querySelectorAll('pre code').forEach((block) => {
Maybe we can be more selective? By adding another class named after the plugin?

2024-09-05 20:06 UTC, maximehuran commented on src/Twig/RichEditorExtension.php
> +        if (!$isValid) {
Spotted by PHP Stan

2024-09-06 06:44 UTC, delyriand approved these changes

2024-09-06 07:33 UTC, lanfisis approved these changes

2024-09-06 07:35 UTC, welcoMattic commented on README.md
> +Use can use `MONSIEURBIZ_SYLIUS_RICH_EDITOR_ENABLED_HIGHLIGHT_JS_SHOP` to enable code highlighting in the shop.
```suggestion
You can use `MONSIEURBIZ_SYLIUS_RICH_EDITOR_ENABLED_HIGHLIGHT_JS_SHOP` to enable code highlighting in the shop.
```

2024-09-06 07:35 UTC, welcoMattic commented on scripts/replace_intl_extension.php
> +    if (false === $realPath || !file_exists($realPath)) {
```suggestion
    if (!$realPath || !file_exists($realPath)) {
```

2024-09-06 07:35 UTC, welcoMattic commented on src/Resources/views/Shop/app.html.twig
> +    {% include '@SyliusUi/_javascripts.html.twig' with {'path': 'bundles/monsieurbizsyliusricheditorplugin/js/rich-editor-highlight.js'} %}
```suggestion
    {{ include('@SyliusUi/_javascripts.html.twig', {'path': 'bundles/monsieurbizsyliusricheditorplugin/js/rich-editor-highlight.js'}) %}
```

Same for the next `include` below

2024-09-06 08:43 UTC, merged