Update v2 upgrade docs
monsieurbiz/SyliusRichEditorPlugin pull request #96
Opened 2020-11-13 18:16 UTC by DieterHolvoet

I noticed this change when updating the plugin.

2020-11-14 13:36 UTC, jacquesbh requested changes
Thank you @DieterHolvoet!

Could you just use a diff code block instead of a simple yaml?

Great catch!

2020-11-14 13:36 UTC, jacquesbh commented on UPGRADE-2.0.md
> +```
Having a diff would be great!

2020-11-18 10:53 UTC, DieterHolvoet commented on UPGRADE-2.0.md
> +```
I replaced it with a diff.

2020-11-18 15:21 UTC, jacquesbh requested changes
Hey @DieterHolvoet!

Thank you for this PR. Last time I was in a hurry and didn't perform a full review, sorry about that.

Here are some quick changes I suggest.

Thank you!

2020-11-18 15:21 UTC, jacquesbh commented on UPGRADE-2.0.md
You could add as well:

```
The file `config/routes/monsieurbiz_sylius_rich_editor.yaml` was renamed to `config/routes/monsieurbiz_sylius_rich_editor_plugin.yaml`.  
The file `config/packages/monsieurbiz_sylius_rich_editor.yaml` was renamed to `config/packages/monsieurbiz_sylius_rich_editor_plugin.yaml`.

2020-11-18 15:21 UTC, jacquesbh commented on UPGRADE-2.0.md
> +## Twig function
```suggestion
## Twig function

```

2020-11-18 15:21 UTC, jacquesbh commented on UPGRADE-2.0.md
> +## JavaScript
```suggestion
## JavaScript

```

2020-11-18 15:21 UTC, jacquesbh commented on UPGRADE-2.0.md
> +The JavaScript was refactored, now it works everywhere. You shouldn't have to change anything, the bundle system will take care of it.
```suggestion
The JavaScript was refactored, now it works everywhere. You shouldn't have to change anything, the bundle system will take care of it.  
But if you made some changes to the previous JS, you'll have to apply them on the new JS. It is a complete rewrite.
```

2020-11-18 15:21 UTC, jacquesbh commented on UPGRADE-2.0.md
> +## UI elements
```suggestion
## UI elements

```

2020-11-25 13:42 UTC, maximehuran commented
@DieterHolvoet can you resolve the conflict ? :)

2020-11-25 17:15 UTC, DieterHolvoet commented
Done!

2020-11-25 17:34 UTC, jacquesbh approved these changes

2020-11-26 10:35 UTC, maximehuran approved these changes

2020-11-26 10:35 UTC, merged

2020-11-26 10:36 UTC, maximehuran commented
Thank you @DieterHolvoet 🚀